--
-- Name: tb_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_categories (
    id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: tb_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_order_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_order_item (
    price double precision,
    quantity integer,
    product_id bigint NOT NULL,
    order_id bigint NOT NULL
);


--
-- Name: tb_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_orders (
    id bigint NOT NULL,
    moment timestamp without time zone,
    order_status integer,
    client_id bigint
);


--
-- Name: tb_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_payment (
    moment timestamp without time zone,
    order_id bigint NOT NULL
);


--
-- Name: tb_product_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_product_category (
    product_id bigint NOT NULL,
    category_id bigint NOT NULL
);


--
-- Name: tb_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_products (
    id bigint NOT NULL,
    description character varying(255),
    img_url character varying(255),
    name character varying(255),
    price double precision
);


--
-- Name: tb_products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_users (
    id bigint NOT NULL,
    email character varying(255),
    name character varying(255),
    password character varying(255),
    phone character varying(255)
);


--
-- Name: tb_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_categories tb_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_categories
    ADD CONSTRAINT tb_categories_pkey PRIMARY KEY (id);


--
-- Name: tb_order_item tb_order_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_order_item
    ADD CONSTRAINT tb_order_item_pkey PRIMARY KEY (order_id, product_id);


--
-- Name: tb_orders tb_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_orders
    ADD CONSTRAINT tb_orders_pkey PRIMARY KEY (id);


--
-- Name: tb_payment tb_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_payment
    ADD CONSTRAINT tb_payment_pkey PRIMARY KEY (order_id);


--
-- Name: tb_product_category tb_product_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_product_category
    ADD CONSTRAINT tb_product_category_pkey PRIMARY KEY (product_id, category_id);


--
-- Name: tb_products tb_products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_products
    ADD CONSTRAINT tb_products_pkey PRIMARY KEY (id);


--
-- Name: tb_users tb_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_users
    ADD CONSTRAINT tb_users_pkey PRIMARY KEY (id);


--
-- Name: tb_order_item fk11kgiid478vipvuwfkxs47t86; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_order_item
    ADD CONSTRAINT fk11kgiid478vipvuwfkxs47t86 FOREIGN KEY (product_id) REFERENCES public.tb_products(id);


--
-- Name: tb_product_category fkeaxc016dqii836yl4ue7ev8j5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_product_category
    ADD CONSTRAINT fkeaxc016dqii836yl4ue7ev8j5 FOREIGN KEY (category_id) REFERENCES public.tb_categories(id);


--
-- Name: tb_payment fkexoo1j7qmu0x3y9nwpc6nfcfx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_payment
    ADD CONSTRAINT fkexoo1j7qmu0x3y9nwpc6nfcfx FOREIGN KEY (order_id) REFERENCES public.tb_orders(id);


--
-- Name: tb_orders fkjbtk96a5pyaj3qx3bmgvghksg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_orders
    ADD CONSTRAINT fkjbtk96a5pyaj3qx3bmgvghksg FOREIGN KEY (client_id) REFERENCES public.tb_users(id);


--
-- Name: tb_product_category fkq8plupmr9wr1q1vy31m9b0v90; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_product_category
    ADD CONSTRAINT fkq8plupmr9wr1q1vy31m9b0v90 FOREIGN KEY (product_id) REFERENCES public.tb_products(id);


--
-- Name: tb_order_item fktmhbubg77mp2f25ujbk202agv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_order_item
    ADD CONSTRAINT fktmhbubg77mp2f25ujbk202agv FOREIGN KEY (order_id) REFERENCES public.tb_orders(id);


--
-- PostgreSQL database dump complete
--

